In [2]:
# NumPy Array Creation
""" This file demonstrates different ways to create arrays using NumPy.
Numpy array is like container that holds number in an organized way (1D,2D,3D etc)
In computer programming, an array is a structure for storing and retrieving data. 


     We can visualize 1D array like 
     ----------------------
     |      |      |       |
     |   1  | 2    |  3    |
      ---------------------
"""

import numpy as np

# 1. Creating a 1D Array
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"1D Array:\n{arr_1d}")
'''
Output:
1D Array:
[10 20 30 40 50]
'''

# Array Indexing - Accessing Elements in 1D Array  indexing in array start with zero
print(f"Element at index 2 in 1D Array: {arr_1d[2]}")  



1D Array:
[10 20 30 40 50]
Element at index 2 in 1D Array: 30


In [4]:
# 2. Creating a 2D Array
"""
    Visualization of a 2D Array (3 columns × 2 rows):
    -------------------
    |  1  |  2  |  3  |    this we row we called as 0
    -------------------
    |  4  |  5  |  6  |    this row we called as 1
    -------------------
    Row 0     Row 1
"""

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr_2d}")


# Array Indexing - Accessing Elements in 2D Array
print(f"Element at position (1, 2): {arr_2d[1, 2]}")  

2D Array:
[[1 2 3]
 [4 5 6]]
Element at position (1, 2): 6


In [6]:
# 3. Creating a 3D Array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr_3d}")



# Array Indexing - Accessing Elements in 3D Array
print(f"Element at position (1, 1, 1): {arr_3d[1, 1, 1]}")  # Output: 8

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Element at position (1, 1, 1): 8


In [12]:
# 4. Higher Dimensional Arrays (4D and beyond)
arr_4d = np.zeros((2, 3, 4, 5))  # Creating a 4D array of zeros with shape (2, 3, 4, 5)
print(f"4D Array of zeros:\n{arr_4d}")




4D Array of zeros:
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [9]:
# 5. Using zeros to create an array filled with zeros
arr_zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print(f"Array of zeros:\n{arr_zeros}")


Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 6. Using ones to create an array filled with ones
arr_ones = np.ones((2, 3))  # 2 rows, 3 columns
print(f"Array of ones:\n{arr_ones}")

Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
