In [10]:
import numpy as np
import random

random_array=np.random.randint(1,12,(3,3))
print(random_array)

if random_array<5:
    print(random_array=0).all()
# else:
#     print(random_array).any()

[[ 8  5 10]
 [ 8  1  9]
 [10  3 11]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()