In [1]:
#NumPy Operations
#NumPy is a powerful library for numerical operations in python

#ndim
'''
    also called as Number of Dimensions
    It is used to find the dimension of the array(row*column)

'''
import numpy as np
arr=np.array([(2,3,4),(2,3,3)])
print(arr.ndim)

2


In [2]:

#Size
'''
    Size attribute returns the total (number of elements) in the array.
    where all dimensions are combined.
'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)  # Output: 6 (2 *3=6 elements)


6


In [7]:
#shape
'''
    shape attribute returns a tuple representing the (dimensions of the array)
    (row,columns)
'''
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"The shape of array is {arr.shape}")

a = np.array([(4,4,4),(5,5,5),(6,6,6),(7,7,7)])
print(f"The dimension of arry is:{a.ndim}") 
print(f"The size of array is {a.size}") 
print(f"The shape of array is {a.shape}") 

The shape of array is (2, 3)
The dimension of arry is:2
The size of array is 12
The shape of array is (4, 3)


In [8]:
#reshape
'''
     The reshape() function is used to change the shape of an array without altering its data. 
     The total number of elements in the reshaped array must remain the same as the original array
     otherwise it returns error
'''
print(a.reshape(4,3))

[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]


In [13]:
arra = np.array([1,2,3],[4,5])
print(arra.reshape(3,2))
'''
ValueError: cannot reshape array of size 12 into shape (3,2)

TypeError: Field elements must be 2- or 3-tuples, got '4'
'''

TypeError: Field elements must be 2- or 3-tuples, got '4'