In [1]:
#slcicing
'''
    Slcicing is basically extracting particular set of elements from an array.
    syntax:
    array[start:stop:step]

'''
#slicing 1D Array
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr[0:4])   #[10 20 30 40]
print(arr[-4:-1]) #[40 50 60]




[10 20 30 40]
[40 50 60]


In [3]:

#slicing 2D Array
arra=np.array([(1,2,3,4),(3,4,5,6)])
print(arra[0,2])  #3
print(arra[1:3])  
print(arra[0:,2]) #[3,5]

3
[[3 4 5 6]]
[3 5]


In [4]:
#linespace
'''
    This is another operation in python numpy which returns evenly spaced 
    numbers over a specified interval
'''
import numpy as np
a=np.linspace(2,10,5)
arr=np.linspace(1,9,5)
print(a)   #[ 2.  4.  6.  8. 10.]
print(arr) #[1. 3. 5. 7. 9.]

#This code has printed 5 values between 2 to 10

[ 2.  4.  6.  8. 10.]
[1. 3. 5. 7. 9.]
