In [2]:
# Mathematical Functions in NumPy
# Basic Statistical Functions

import numpy as np

# Creating a 2D array
arr = np.array([[1, 2], [3, 4]])

# 1. Sum of all elements
'''
The np.sum() function returns the sum of all the elements in the array.
'''
print(np.sum(arr))  # Output: 10 (1+2+3+4)

# 2. Mean of all elements
'''
The np.mean() function computes the average (mean) of all the elements in the array.
'''
print(np.mean(arr))  # Output: 2.5 (mean of 1, 2, 3, 4)

# 3. Median of all elements
'''
The np.median() function computes the median of the array (middle value).
'''
print(np.median(arr))  # Output: 2.5 (middle value of 1, 2, 3, 4)

# 4. Standard Deviation
'''
The np.std() function calculates the standard deviation, measuring how spread out the values are.
'''
print(np.std(arr))  # Output: 1.118033988749895 (standard deviation of 1, 2, 3, 4)

# Creating a 1D array for max and min operations
a = np.array([100, 22, 31])

# 5. Maximum value
'''
The np.max() function returns the largest value in the array.
'''
print(np.max(a))  # Output: 100 (largest value in [100, 22, 31])

# 6. Minimum value
'''
The np.min() function returns the smallest value in the array.
'''
print(np.min(a))  # Output: 22 (smallest value in [100, 22, 31])

# 7. Square root of each element
'''
The np.sqrt() function computes the square root of each element in the array.
'''
print(np.sqrt(a))  # Output: [10.    4.69041576  5.56776436] (square root of 100, 22, and 31)

#8. Additional/Subtraction
'''
The operation of Numpy array i.e add,sub,mul and div of two matrics 
can be determined.
'''
x=np.array([(18,2,3),(3,49,5)])
y=np.array([(13,28,3),(63,4,5)])
print("Add:",x+y)
print("sub:",x-y)
print("Mul:",x*y)
print("Div:",x/y)
'''
Add: [[31 30  6]
 [66 53 10]]
sub: [[  5 -26   0]
 [-60  45   0]]
Mul: [[234  56   9]
 [189 196  25]]
Div: [[ 1.38461538  0.07142857  1.        ]
 [ 0.04761905 12.25        1.        ]]

'''




10
2.5
2.5
1.118033988749895
100
22
[10.          4.69041576  5.56776436]
Add: [[31 30  6]
 [66 53 10]]
sub: [[  5 -26   0]
 [-60  45   0]]
Mul: [[234  56   9]
 [189 196  25]]
Div: [[ 1.38461538  0.07142857  1.        ]
 [ 0.04761905 12.25        1.        ]]


'\nAdd: [[31 30  6]\n [66 53 10]]\nsub: [[  5 -26   0]\n [-60  45   0]]\nMul: [[234  56   9]\n [189 196  25]]\nDiv: [[ 1.38461538  0.07142857  1.        ]\n [ 0.04761905 12.25        1.        ]]\n\n'

In [4]:
# Rounding operations
decimals = np.array([1.23, 4.67, 8.91])
print(np.round(decimals))     # round to nearest integer
print(np.floor(decimals))     # round down
print(np.ceil(decimals))      # round up

[1. 5. 9.]
[1. 4. 8.]
[2. 5. 9.]


In [3]:
# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # sine
print(np.cos(angles))  # cosine
print(np.tan(angles))  # tangent

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [5]:
# Exponential and logarithmic
arr = np.array([1, 2, 3])
print(np.exp(arr))      # e^x
print(np.log(arr))      # natural log
print(np.log10(arr))    # base-10 log
print(np.power(arr, 2)) # power function

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[1 4 9]
