In [3]:
import numpy as np

In [4]:
#Create a NumPy array from the list [7,14,21,28]. Print the array.

arr = np.array([7,14,21,28])
print(arr)


[ 7 14 21 28]


In [5]:
#Create a 2D NumPy array [[5,10,15],[20,25,30]]. Print its shape and number of dimensions.

arr = np.array([[5,10,15],[20,25,30]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [6]:
#Use np.zeros to create a 2D array of shape (2,3). Then, use np.arange to create an array from 0 to 12 with a step of 3. Print both arrays.

a = np.zeros((2,3))
b = np.arange(0,13,3)
print(a)
print("\n")
print(b)
     

[[0. 0. 0.]
 [0. 0. 0.]]


[ 0  3  6  9 12]


In [7]:
#Create a NumPy array [2,4,6,8]. Multiply all elements by 3 and print the result.

a = np.array([2,4,6,8])
b = a*3
print(b)

[ 6 12 18 24]


In [8]:
#Create a NumPy array [1,3,5,7,9,11]. Print the third element and a slice from index 1 to 3 (inclusive).

a = np.arange(1,12,2)
print("Third element = ", end = " ")
print(a[2])
print("\nSlice form index 1 to 3 (inclusive) =", end= " ")
print(a[1:4])
     

Third element =  5

Slice form index 1 to 3 (inclusive) = [3 5 7]


In [9]:
#Create a 2D Numpy array of shape (3,3) with random integers between 1 and 10 (inclusive) using np.random.randint. Then, replace all values greater than 5 aith 0 and print the modified array.

arr = np.random.randint(1,11,(3,3))
print(arr)
arr[arr>5] = 0
print("\nModified array:")
print(arr)

[[8 1 8]
 [1 5 1]
 [1 3 6]]

Modified array:
[[0 1 0]
 [1 5 1]
 [1 3 0]]


In [10]:
#Create two 1D NumPy arrays: [2,4,6,8] and [1,3,5,7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.

a = np.array([2,4,6,8])
b = np.array([1,3,5,7])

sum = a+b
product = a*b
print(sum)
print(product)
     

[ 3  7 11 15]
[ 2 12 30 56]


In [14]:
#Create a 2D NumPy array of shape (4,3) filled with ones using np.ones. Then, add a 1D array [10,20,30] to each row of the 2D array using broadcadting. Print the resulting array.

a = np.ones((4,3))
b = np.array([10,20,30])

new_arr = a+b

print(new_arr)
     

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [15]:
#Create a 2D NumPy array [[1,2,3],[4,5,6],[7,8,9]]. Extract the second column and compute its mean using np.mean. Then, reshape the original array into a 1D array and print both results.

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
mean_value = np.mean(a[:,1])
print(mean_value)

new_arr = np.array(a).reshape(-1)
print(new_arr)

5.0
[1 2 3 4 5 6 7 8 9]


In [16]:
#Create a 1D NumPy array [10, 20, 30 ,40, 50, 60]. Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.

a = np.array([10, 20, 30 ,40, 50, 60])
mask = a>30
new_arr = a[mask]**2
print(a)
print(new_arr)
    

[10 20 30 40 50 60]
[1600 2500 3600]


In [ ]:

"""
Remaining to do

    ✅ Basic Level
Create an array of even numbers from 2 to 20.

Create a 1D array of 10 zeros and change the 5th value to 99.

Reverse a 1D array without using loops.

Check the data type of each element in an array.

Convert a Python list [1.1, 2.2, 3.3] to an integer array.

🟡 Intermediate Level
Generate a 4×4 identity matrix.

Create a 5×5 array with random integers from 0 to 100 and find the maximum value in each row.

Normalize an array (scale values between 0 and 1).

Replace all even numbers in an array with -1 without a loop.

Count the number of elements greater than 50 in a random array of 100 values.

🔵 Advanced Level
Find the common elements between two NumPy arrays.

Find the row-wise and column-wise sum of a 3x3 matrix.

Replace the diagonal elements of a matrix with 0.

Create a 2D array and compute the cumulative sum along the rows and columns.

Sort a 2D array by a specific column (e.g., sort by second column).

🧠 Bonus: Real-World Type Mini Tasks
Create a temperature dataset and convert Celsius to Fahrenheit using vectorized operations.

Simulate a dice roll (6-sided) 1000 times and count frequency of each face.

Given salary data in an array, filter out employees earning more than average.

Create a 10×10 matrix and replace the border with 1s and the inner cells with 0.

Split a 1D array of size 20 into 4 equal parts and reshape each into (2, 2).
"""